micronaut:
  application:
    name: demo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/hexagonal
    driverClassName: org.postgresql.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: POSTGRES

netty:
  default:
    allocator:
      max-order: 3

jpa.default.properties.hibernate.hbm2ddl.auto: create
